### ISSUE TITLE
Can't use type aliases to distinguish values of same interface

### ISSUE THREAD

**Issue by nyarly** [samsalisbury/psyringe#1]
I tried this (effectively): 

```
type OutWriter io.Writer
type ErrWriter io.Writer

psyringe.New(OutWriter(os.Stdout), ErrWriter(os.Stderr))
```

and got a panic:

```
panic: Add failed: adding *bytes.Buffer value failed: injection type *bytes.Buffer already registered 
```

**Comment by nyarly** [comment]
The workaround I found was to wrap the values in a function, _comme ça:_

```
psyringe.New(func() OutWriter { return os.Stdout }, func() ErrWriter( return os.Stderr))
```

**Comment by samsalisbury** [comment]
Yes, this is by design but should be better documented.

When adding a non-constructor, the underlying value is used (via reflect.ValueOf). Thus you can either do as you did (wrap in a func and use its return type) or wrap as an anonymous field in a new struct type.

It may be possible to support this use case directly by reading the [interface data](https://golang.org/pkg/reflect/#Value.InterfaceData).
